### PR TITLE
add stddev_pop(), stddev_samp(), var_pop(), var_samp() functions

### PR DESCRIPTION
**Pull request by nakagami**
Part of Aggregate Functions
http://www.postgresql.org/docs/9.3/static/functions-aggregate.html#FUNCTIONS-AGGREGATE-STATISTICS-TABLE

Test code
https://gist.github.com/nakagami/859e0cb70ba3109d353e

### CODE REVIEW

**Comment by asfernandes** [comment]
keywords.cpp: version field should be 2 instead of 1.

val.h: Instead of add things to impure_value_ex, you'd better create a specific struct inside StdDevAggNode.

blr.h: Use the blr_agg_* prefix.

parse.y: new keywords should be added to keyword_or_column rule.

AggNodes.cpp: Initialize tempImpure(0) in StdDevAggNode constructor.
AggNodes.cpp: In StdDevAggNode::parse add a default with fb_assert.

I'm not sure about these functions always return double. PgSQL documentation you referenced says a different thing. But the standard say:

If VAR_POP or VAR_SAMP is specified, then the declared type of the result is an implementation-
defined approximate numeric type. If DT is an approximate numeric type, then the precision of the
result is not less than the precision of DT.

STDDEV_POP(X) is equivalent to SQRT(VAR_POP(X)).
STDDEV_SAMP(X) is equivalent to SQRT(VAR_SAMP(X)).

So maybe is ok. What others fb-devs think?

Also seems that per the standard, DISTINCT is not valid in these functions:

Neither DISTINCT nor ALL are allowed to be specified for VAR_POP, VAR_SAMP, STDDEV_POP, or
STDDEV_SAMP; redundant duplicates are not removed when computing these functions.

We need documentation. See for example doc/sql.extension/README.window_functions.txt as an example.

**Comment by asfernandes** [comment]
An entry should be added in src/jrd/blp.h

**Comment by AlexPeshkoff** [comment]
I see no reason why should rule for choosing a type of the value, returned by this functions, differ from one used for other aggregates - type of return same value matches argument.

**Comment by dyemanov** [comment]
Alex, this is not always the case. For example, SUM() returns the type one step "bigger" than its argument. COUNT() returns BIGINT regardless of the input argument type. So I think it's OK that every aggregate function defines its own rules for the resulting type.

PGSQL handles this interestingly: it returns NUMERIC for any fixed-point input. I suppose they preserve the scale but the question is whether they also preserve the precision or extend it. And what NUMERIC(X, Y) they return for exact inputs (smallint/int/bigint). I think we need to check this before making a decision. And probably check other DBMS vendors too.

**Comment by dyemanov** [comment]
MSSQL: non-standard syntax, resulting type is always float, DISTINCT is allowed.
Oracle: resulting type is the same as the input argument, DISTINCT is not allowed.
DB2: resulting type is always double precision, DISTINCT is not allowed.

Personally, I think that DISTINCT/ALL should be prohibited. As for the resulting type, I'd go along with the SQL spec for double precision.

**Comment by asfernandes** [comment]
The test I did with PGSQL was with integer inputs and it returns something like double, so it may be a numeric with large precision, or something like Oracle NUMBER. Something we do not support well.

I also think we should return double and do not support DISTINCT/ALL.

**Comment by nakagami** [comment]
Well, fix it.

1. Always return double (not changed) and do not support DISTINCT/ALL.
2. Sorry, documentation, I want someone's help about english.

BTW

>AggNodes.cpp: In StdDevAggNode::parse add a default with fb_assert.

Sorry I don't know what I do. Please teache me in detail

**Comment by asfernandes** [comment]
Documentation: just some description of the functions, it will be reviewed for the release notes. But please don't copy someone else copyrighted material.

In StdDevAggNode::parse, just this may be sufficient in the switch:

default:
    fb_assert(false);

**Comment by asfernandes** [comment]
I see now you had already wrote the documentation. It's fine.

**Comment by asfernandes** [comment]
@nakagami I applied the patch with some internal changes, so please test it.

Pull request here cannot be merged, as this github is just a mirror of our svn repository.

Firebird tracker entry: http://tracker.firebirdsql.org/browse/CORE-4714

**Pull request closed without merging**
