### PR TITLE
Add covar_samp(), covar_pop(), corr() functions.

### PR DESCRIPTION
**Pull request by nakagami**
test code https://gist.github.com/nakagami/6b0797350eaf477d4010

### CODE REVIEW

**Comment by asfernandes** [comment]
@nakagami I'm testing this in Firebird and PgSQL:

select covar_samp(n1, 0.1), (SUM(cast(n1 as double precision) * cast(0.1 as double precision)) - SUM(cast(n1 as double precision)) * SUM(cast(0.1 as double precision)) / COUNT(*)) / (COUNT(*) - 1) from t1;

T1 has integer numbers from 1 to 10.

- The second expression works identical in Firebird and PgSQL.
- Both expressions returns the same value in Firebird, so your description matches.

But in PgSQL the two expressions returns different values.

Why?

The same thing happens with the others functions.

**Comment by nakagami** [comment]
Umm, I realise the result, but I don't know why.

I wrote python test code.
https://gist.github.com/nakagami/227c9a91997652180977

```
======================================================================
FAIL: test_pg (__main__.TestCovarSamp)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_covar_samp_pg_and_fb.py", line 31, in test_pg
    self.assertEqual(r[0], r[1])
AssertionError: 1.57898385724467e-16 != 1.97372982155583e-16

----------------------------------------------------------------------
Ran 2 tests in 1.047s
```

**Comment by asfernandes** [comment]
Your expression matches Oracle documentation too. Unfortunately I can not test it for the follow weeks. http://docs.oracle.com/cd/B19306_01/server.102/b14200/functions034.htm

But let see in detail difference between FB and PG:

```
select n1, covar_samp(n1, 0.1) over (order by n1) from t1 order by n1;

FB:

          N1              COVAR_SAMP 
============ ======================= 
           1                  <null> 
           2       0.000000000000000 
           3       0.000000000000000 
           4       0.000000000000000 
           5       0.000000000000000 
           6       0.000000000000000 
           7   7.401486830834377e-17 
           8   1.268826313857322e-16 
           9   2.220446049250313e-16 
          10   1.973729821555834e-16 

PG:

 n1 |      covar_samp      
----+----------------------
  1 |                     
  2 |                    0
  3 |                    0
  4 |                    0
  5 |                    0
  6 |  5.9211894646675e-17
  7 | 8.45884209238214e-17
  8 | 1.26882631385732e-16
  9 | 1.97372982155583e-16
 10 | 1.57898385724467e-16
```

PG start returning values sooner.

Can anyone test others DBMS?

**Comment by nakagami** [comment]
Umm, these logic are seems different ...
Im' sorry test only PG and FB.

**Comment by asfernandes** [comment]
I don't understand what you're saying is different. Did you see anything different in Oracle documentation than what you did?

**Comment by nakagami** [comment]
Oh, sorry, your sample code is correct.
And Oracle's document is correct too, I think.

But FB's result different form PG's result.
FB's computation logic diffent from PG's logic.

**Comment by mariuz** [comment]
You can test it with sqlfiddle http://sqlfiddle.com/

**Comment by nakagami** [comment]
Thanx marius

truncation ?

Oracle 11g R2
```
CREATE TABLE t1 (n1 integer);
INSERT INTO t1 (n1) values (1);
INSERT INTO t1 (n1) values (2);
INSERT INTO t1 (n1) values (3);
INSERT INTO t1 (n1) values (4);
INSERT INTO t1 (n1) values (5);
INSERT INTO t1 (n1) values (6);
INSERT INTO t1 (n1) values (7);
INSERT INTO t1 (n1) values (8);
INSERT INTO t1 (n1) values (9);
INSERT INTO t1 (n1) values (10);

select n1, covar_samp(n1, 0.1) over (order by n1) from t1 order by n1

| N1 | COVAR_SAMP(N1,0.1)OVER(ORDERBYN1) |
|----|-----------------------------------|
|  1 |                            (null) |
|  2 |                                 0 |
|  3 |                                 0 |
|  4 |                                 0 |
|  5 |                                 0 |
|  6 |                                 0 |
|  7 |                                 0 |
|  8 |                                 0 |
|  9 |                                 0 |
| 10 |                                 0 |



CREATE TABLE t1 (n1 double precision);
INSERT INTO t1 (n1) values (1);
INSERT INTO t1 (n1) values (2);
INSERT INTO t1 (n1) values (3);
INSERT INTO t1 (n1) values (4);
INSERT INTO t1 (n1) values (5);
INSERT INTO t1 (n1) values (6);
INSERT INTO t1 (n1) values (7);
INSERT INTO t1 (n1) values (8);
INSERT INTO t1 (n1) values (9);
INSERT INTO t1 (n1) values (10);

select n1, covar_samp(n1, 0.1) over (order by n1) from t1 order by n1

| N1 | COVAR_SAMP(N1,0.1)OVER(ORDERBYN1) |
|----|-----------------------------------|
|  1 |                            (null) |
|  2 |                                 0 |
|  3 |                                 0 |
|  4 |                                 0 |
|  5 |                                 0 |
|  6 |                                 0 |
|  7 |                                 0 |
|  8 |                                 0 |
|  9 |                                 0 |
| 10 |                                 0 |
```

**Comment by asfernandes** [comment]
If you manually do the calculations, you'll see that Oracle is right. Difference between FB and PG seems about internal precision of the calculations.

I don't know if that is good enough.

**Comment by nakagami** [comment]
Second parameter always 0.1 means first(n1) parameter is not related to second parameter.
I think these results means almost 0.

**Comment by nakagami** [comment]
```
CREATE TABLE Samples (x integer, y integer);
INSERT INTO Samples(x, y) VALUES (3,9);
INSERT INTO Samples(x, y) VALUES (2,7);
INSERT INTO Samples(x, y) VALUES (4,12);
INSERT INTO Samples(x, y) VALUES (5,15);
INSERT INTO Samples(x, y) VALUES (6,17);

SELECT COVAR_SAMP(x, y) FROM Samples;
```

FB
```
             COVAR_SAMP
=======================
      6.500000000000000
```

PG
```
 covar_samp
------------
        6.5
(1 row)
```

Oracle
```
COVAR_SAMP(X,Y)
6.5
```

**Comment by asfernandes** [comment]
Ok, so maybe I just choose incoherent numbers to test.

I verified that CORR(2, 7) was returning NaN instead of NULL in Oracle and PgSQL and did a change. Please verify its correctness in my commit.

Tracker entry: http://tracker.firebirdsql.org/browse/CORE-4717

**Comment by nakagami** [comment]
Thanks
Looking good

**Pull request closed without merging**
